let RoleTypes = {
    NULL: "NULL",
    ROLE_CLIENT: "ROLE_CLIENT",
    ROLE_ADMIN_SERVICE_VEHICLE   : "ROLE_ADMIN_SERVICE_VEHICLE",
    ROLE_ADMIN_SERVICE_HOTEL  :"ROLE_ADMIN_SERVICE_HOTEL",
    ROLE_ADMIN_SERVICE_USER  :"ROLE_ADMIN_SERVICE_USER",
    ROLE_ADMIN_SERVICE_TRAVELPACKAGE  :"ROLE_ADMIN_SERVICE_TRAVELPACKAGE",
    ROLE_ADMIN_SERVICE_GUIDE  :"ROLE_ADMIN_SERVICE_GUIDE"
}